### ISSUE TITLE
Add issue and PR templates

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/OCRed#68]
References -
- Files -  https://github.com/pybamm-team/PyBaMM/tree/develop/.github | New issue - https://github.com/pybamm-team/PyBaMM/issues/new/choose
- Files - https://github.com/scikit-hep/pyhf/tree/master/.github | New issue - https://github.com/Scikit-hep/pyhf/issues/new/choose
- Files - https://github.com/scikit-hep/awkward/tree/main/.github | New issue - https://github.com/Scikit-hep/awkward/issues/new/choose

Issue template files are in the folder `ISSUE_TEMPLATE/`, and the PR template is named as `PULL_REQUEST_TEMPLATE.md`.

**Comment by Vaibhav-Chopra-GT** [comment]
Can I work on this issue?
